FROM ubuntu:18.04

RUN apt update \
 && apt install -y \
    curl \
    gnupg \
    gcc \
    g++ \
    make \
 && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
 && apt install -y nodejs \
 && rm -rf /var/lib/apt/lists/*

RUN npm install --global yarn

ADD . /botpress

WORKDIR /botpress

ENV EDITION=ce

RUN yarn && yarn build

EXPOSE 3000

CMD ["npm run start"]